<div>
    <div data-bind="scope: 'checkout_fields_manager.checkout_fields_manager'">
        <input
            id="gomage_light_checkout_configuration_checkout_address_fields_sorting_fields_manager"
            name="groups[checkout_address_fields_sorting][fields][fields_manager][value]"
            class="validate-lightcheckout-fields-manager input-text admin__control-text"
            type="hidden"
            data-bind="value: inputValue"
        >
        <br>
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
