<div>
    <div data-role="spinner" data-component="checkout_fields_manager.areas" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span/><span/><span/><span/><span/><span/><span/><span/>
        </div>
    </div>
    <div data-bind="scope: 'checkout_fields_manager.areas'" class="entry-edit form-inline">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
